/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '28/01/16 10:23' with Gradle 2.6
 *
 * @author mati, @date 28/01/16 10:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
